# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Oddyssey Studio
email: info@oddysseystudio.com
description: > 
    We are student and ex-student from the Game Development School Event Horizon with a 
    past in other narrative media. Our game have a deeper layer of entertainment, 
    there for everyone who want to look and find an amazing story other than a unique game.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://oddysseystudio.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: oddysseystudio
github_username:  OddysseyStudio

# Build settings
markdown: kramdown
encoding: utf-8

plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock

# Repository
repository: "OddysseyStudio/oddysseystudio.github.io"

# Keep File
keep_files: ["images"]

# Include
include: [".htaccess"]

twitter:
    page: oddysseystudio

fb:
    #admins: nothing
    #publisher: nothing
    app_id: 0000
    page: oddysseystudio
    
#google_verification: 

# Source Images
images:
    defualt: "https://oddysseystudio.github.io/images/"
    member: "https://oddysseystudio.github.io/images/members/"
    mini: "https://oddysseystudio.github.io/images/hero/thumb/th-"
    site: "https://oddysseystudio.github.io/images/site.jpg"